ServerName localhost

<Directory /app/yii2/backend/web>
    Options FollowSymLinks
    AllowOverride None
    Require all granted
    DirectoryIndex index.php
    FallbackResource /index.php
</Directory>
