#!/usr/bin/env php
<?php

/**
 * Yii console bootstrap file.
 */

use Dotenv\Dotenv;
use yii\helpers\ArrayHelper;
use yii\console\Application as AppConsole;

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require __DIR__ . '/../vendor/autoload.php';

Dotenv::createImmutable(__DIR__, '.env')->load();

require __DIR__ . '/../vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/common/config/bootstrap.php';
require __DIR__ . '/console/config/bootstrap.php';

$config = ArrayHelper::merge(
    require __DIR__ . '/common/config/main.php',
    require __DIR__ . '/common/config/main-local.php',
    require __DIR__ . '/console/config/main.php',
    require __DIR__ . '/console/config/main-local.php'
);

$app = new AppConsole($config);

$exitCode = $app->run();

exit( $exitCode );
