#!/usr/bin/env php
<?php

/**
 * Yii console bootstrap file.
 */

use Dotenv\Dotenv;
use yii\helpers\ArrayHelper;
use yii\console\Application as AppConsole;

defined('YII_DEBUG') or define('YII_DEBUG', false);
defined('YII_ENV') or define('YII_ENV', 'prod');

require __DIR__ . '/vendor/autoload.php';

Dotenv::createImmutable( __DIR__, '.env')->load();

require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/app/common/config/bootstrap.php';
require __DIR__ . '/app/console/config/bootstrap.php';

$config = ArrayHelper::merge(
    require __DIR__ . '/app/common/config/main.php',
    require __DIR__ . '/app/common/config/main-local.php',
    require __DIR__ . '/app/console/config/main.php',
    require __DIR__ . '/app/console/config/main-local.php'
);

exit(
    (new AppConsole($config))
        ->run()
);
