<?php declare(strict_types=1);

/**
 * Full separated mapping for the file crafter generator.
 */

$relationStyle  = [
    'app/common/services/ItemService' => 'app/common/services/items/{{PascalCase}}Service.php',
    'app/frontend/services/ItemService' => 'app/frontend/services/items/{{PascalCase}}Service.php',
    'app/backend/services/ItemService' => 'app/backend/services/items/{{PascalCase}}Service.php',
    'app/console/services/ItemService' => 'app/console/services/items/{{PascalCase}}Service.php',
];

return [
    'relationStyle' => $relationStyle,
    'all' => array_merge($relationStyle,[
        'app/common/services/ItemRepository' => 'app/common/services/repositories/{{PascalCase}}Repository.php',
        'app/common/services/ItemProvider' => 'app/common/services/providers/{{PascalCase}}Provider.php',
        'app/common/components/dataProviders/ItemDataProvider' => 'app/common/components/dataProviders/items/{{PascalCase}}DataProvider.php',
        'app/common/tests/unit/models/items/ItemTest' => 'app/common/tests/unit/models/{{PascalCase}}Test.php',
        'app/common/tests/unit/services/ItemRepositoryTest' => 'app/common/tests/unit/services/repositories/{{PascalCase}}RepositoryTest.php',
        'app/common/tests/unit/services/ItemProviderTest' => 'app/common/tests/unit/services/providers/{{PascalCase}}ProviderTest.php',
        'app/common/tests/unit/services/ItemServiceTest' => 'app/common/tests/unit/services/items/{{PascalCase}}ServiceTest.php',
        'app/console/ItemController' => 'app/console/controllers/{{PascalCase}}Controller.php',
        'app/console/services/ItemRepository' => 'app/console/services/repositories/{{PascalCase}}Repository.php',
        'app/console/services/ItemProvider' => 'app/console/services/providers/{{PascalCase}}Provider.php',
        'app/console/tests/unit/services/ItemRepositoryTest' => 'app/console/tests/unit/services/repositories/{{PascalCase}}RepositoryTest.php',
        'app/console/tests/unit/services/ItemProviderTest' => 'app/console/tests/unit/services/providers/{{PascalCase}}ProviderTest.php',
        'app/console/tests/unit/services/ItemServiceTest' => 'app/console/tests/unit/services/items/{{PascalCase}}ServiceTest.php',
        'app/frontend/ItemController' => 'app/frontend/controllers/{{PascalCase}}Controller.php',
        'app/frontend/resources/ItemIndexResource' => 'app/frontend/resources/{{PascalCase}}IndexResource.php',
        'app/frontend/resources/ItemViewResource' => 'app/frontend/resources/{{PascalCase}}ViewResource.php',
        'app/frontend/views/index' => 'app/frontend/views/{{snake_case}}/index.php',
        'app/frontend/views/view' => 'app/frontend/views/{{snake_case}}/view.php',
        'app/frontend/services/ItemRepository' => 'app/frontend/services/repositories/{{PascalCase}}Repository.php',
        'app/frontend/services/ItemProvider' => 'app/frontend/services/providers/{{PascalCase}}Provider.php',
        'app/frontend/tests/unit/models/ItemTest' => 'app/frontend/tests/unit/models/{{PascalCase}}Test.php',
        'app/frontend/tests/unit/services/ItemRepositoryTest' => 'app/frontend/tests/unit/services/repositories/{{PascalCase}}RepositoryTest.php',
        'app/frontend/tests/unit/services/ItemProviderTest' => 'app/frontend/tests/unit/services/providers/{{PascalCase}}ProviderTest.php',
        'app/frontend/tests/unit/services/ItemServiceTest' => 'app/frontend/tests/unit/services/items/{{PascalCase}}ServiceTest.php',
        'app/frontend/tests/unit/resources/ItemIndexResourceTest' => 'app/frontend/tests/unit/resources/{{PascalCase}}IndexResourceTest.php',
        'app/frontend/tests/unit/resources/ItemViewResourceTest' => 'app/frontend/tests/unit/resources/{{PascalCase}}ViewResourceTest.php',
        'app/frontend/tests/functional/ItemControllerCest' => 'app/frontend/tests/functional/{{PascalCase}}ControllerCest.php',
        'app/frontend/tests/acceptance/ItemControllerCest' => 'app/frontend/tests/acceptance/{{PascalCase}}ControllerCest.php',
        'app/backend/ItemController' => 'app/backend/controllers/{{PascalCase}}Controller.php',
        'app/backend/resources/ItemIndexResource' => 'app/backend/resources/{{PascalCase}}IndexResource.php',
        'app/backend/resources/ItemViewResource' => 'app/backend/resources/{{PascalCase}}ViewResource.php',
        'app/backend/resources/ItemFormResource' => 'app/backend/resources/{{PascalCase}}FormResource.php',
        'app/backend/resources/ItemSearchResource' => 'app/backend/resources/{{PascalCase}}SearchResource.php',
        'app/backend/resources/ItemCreateResource' => 'app/backend/resources/{{PascalCase}}CreateResource.php',
        'app/backend/resources/ItemUpdateResource' => 'app/backend/resources/{{PascalCase}}UpdateResource.php',
        'app/backend/views/index' => 'app/backend/views/{{snake_case}}/index.php',
        'app/backend/views/view' => 'app/backend/views/{{snake_case}}/view.php',
        'app/backend/views/form' => 'app/backend/views/{{snake_case}}/form.php',
        'app/backend/views/search' => 'app/backend/views/{{snake_case}}/search.php',
        'app/backend/views/create' => 'app/backend/views/{{snake_case}}/create.php',
        'app/backend/views/update' => 'app/backend/views/{{snake_case}}/update.php',
        'app/backend/services/ItemRepository' => 'app/backend/services/repositories/{{PascalCase}}Repository.php',
        'app/backend/services/ItemProvider' => 'app/backend/services/providers/{{PascalCase}}Provider.php',
        'app/backend/tests/unit/models/items/ItemTest' => 'app/backend/tests/unit/models/{{PascalCase}}Test.php',
        'app/backend/tests/unit/services/ItemRepositoryTest' => 'app/backend/tests/unit/services/repositories/{{PascalCase}}RepositoryTest.php',
        'app/backend/tests/unit/services/ItemProviderTest' => 'app/backend/tests/unit/services/providers/{{PascalCase}}ProviderTest.php',
        'app/backend/tests/unit/services/ItemServiceTest' => 'app/backend/tests/unit/services/items/{{PascalCase}}ServiceTest.php',
        'app/backend/tests/unit/resources/ItemIndexResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}IndexResourceTest.php',
        'app/backend/tests/unit/resources/ItemViewResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}ViewResourceTest.php',
        'app/backend/tests/unit/resources/ItemFormResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}FormResourceTest.php',
        'app/backend/tests/unit/resources/ItemSearchResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}SearchResourceTest.php',
        'app/backend/tests/unit/resources/ItemCreateResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}CreateResourceTest.php',
        'app/backend/tests/unit/resources/ItemUpdateResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}UpdateResourceTest.php',
        'app/backend/tests/functional/ItemControllerCest' => 'app/backend/tests/functional/{{PascalCase}}ControllerCest.php',
        'app/backend/tests/acceptance/ItemControllerCest' => 'app/backend/tests/acceptance/{{PascalCase}}ControllerCest.php',
    ]),
];